In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from itertools import product

In [7]:
dtf=['year','month','week','day','dayofweek','dayofyear']

In [4]:
def max_pow (x):
    i=1
    while 2**i<x:
        i+=1
    return(i)

In [11]:
def dt_feath_2_vec(feathers):
    for feather in feathers:
        cat=(pd.read_csv(feather+'.csv')).values
        categories=[]
        for i in cat:    
            categories.extend(i)
        pow=max_pow(len(categories))
        categories.sort()
        a=[]
        for i in product([0,1],repeat=pow):
            a.append(i)
        n=np.array(a)
        e=np.reshape(n, (-1,pow))
        z=np.random.randint(0,(len(categories)),(2**pow-len(categories)))
        for i in z:
            e = np.delete(e, (i), axis=0)
        v_cat=pd.DataFrame(e,index=categories)
        v_cat.to_csv((feather+'_vec'+'.csv'))
        print(v_cat)

In [12]:
dt_feath_2_vec(dtf)

      0
2020  1
   0  1  2  3
1  0  0  1  0
2  0  1  0  0
3  0  1  0  1
4  1  0  0  0
5  1  0  0  1
6  1  0  1  1
7  1  1  0  0
8  1  1  0  1
9  1  1  1  1
    0  1  2  3  4  5
1   0  0  0  0  0  0
2   0  0  0  0  0  1
3   0  0  0  0  1  1
4   0  0  0  1  1  0
5   0  0  0  1  1  1
6   0  0  1  0  0  1
7   0  0  1  0  1  0
8   0  0  1  1  0  0
9   0  0  1  1  0  1
10  0  0  1  1  1  0
11  0  0  1  1  1  1
12  0  1  0  0  0  0
13  0  1  0  0  0  1
14  0  1  0  1  1  1
15  0  1  1  1  0  0
16  0  1  1  1  1  0
17  0  1  1  1  1  1
18  1  0  0  0  0  0
19  1  0  0  0  0  1
20  1  0  0  0  1  1
21  1  0  0  1  0  0
22  1  0  0  1  0  1
23  1  0  1  0  0  0
24  1  0  1  0  1  0
25  1  0  1  0  1  1
26  1  0  1  1  0  0
27  1  0  1  1  0  1
28  1  1  0  0  0  0
29  1  1  0  0  1  1
30  1  1  0  1  0  0
31  1  1  0  1  0  1
32  1  1  0  1  1  0
33  1  1  0  1  1  1
34  1  1  1  0  0  1
35  1  1  1  0  1  0
36  1  1  1  0  1  1
37  1  1  1  1  0  0
38  1  1  1  1  0  1
39  1  1  1  1  1  0
40  

In [2]:
feathers=['application_id','event_type','event_category','event_name','event_label','device_screen_name','timezone','device_is_webview','page_urlhost','page_urlpath_full','net_connection_type','net_connection_tech']

In [3]:
def max_pow (x):
    i=1
    while 2**i<x:
        i+=1
    return(i)

In [35]:
def feath_2_vec(feathers):
    for feather in feathers:
        cat_O=pd.read_csv(feather+'.csv')#.values
        cat_O['0'].fillna('-1', inplace=True)
        #print(cat_O.iloc[0,0])
        #cat_O.iloc[2]='-1' 
        cat=cat_O.values
        categories=[]
        for i in cat:    
            categories.extend(i)
        pow=max_pow(len(categories))
        a=[]
        for i in product([0,1],repeat=pow):
            a.append(i)
        n=np.array(a)
        e=np.reshape(n, (-1,pow))
        z=np.random.randint(0,(len(categories)),(2**pow-len(categories)))
        for i in z:
            e = np.delete(e, (i), axis=0)
        v_cat=pd.DataFrame(e,index=categories)
        v_cat.to_csv((feather+'_vec'+'.csv'))
        print(feather,v_cat,(cat_O['0'].isnull()).value_counts())

In [36]:
feath_2_vec(['page_urlpath_full'])

page_urlpath_full                                   0   1   2   3   4   5   6   7   8   9   10  \
03eb3ceab6204f8b602f1863f7fbce01   0   0   0   0   0   0   0   0   0   0   0   
0aab04d1c6960342cbee1a31a0680312   0   0   0   0   0   0   0   0   0   0   0   
0d1e93db443e0390c9b0b1304dec1548   0   0   0   0   0   0   0   0   0   0   0   
0eba7286124e9d64e4da904d9c0e9448   0   0   0   0   0   0   0   0   0   0   0   
113cb46e3be32ce3d9f1abd632e588f9   0   0   0   0   0   0   0   0   0   0   0   
...                               ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..   
feba754646c041b5943c1a824ace8c17   1   1   1   1   1   1   1   1   1   1   1   
ff1524366fbc175772bcde0e2f41dc59   1   1   1   1   1   1   1   1   1   1   1   
ff3222087213487b33b75b9bb99bd439   1   1   1   1   1   1   1   1   1   1   1   
fff1bd13401c7f07952bccf1824b4fc4   1   1   1   1   1   1   1   1   1   1   1   
eaeaead396d3438849bce7423e9f67e5   1   1   1   1   1   1   1   1   1   1   1   

                     

In [33]:
cat_O=pd.read_csv('page_urlpath_full'+'.csv')
(cat_O['0'].isnull()).value_counts())

False    131675
True          1
Name: 0, dtype: int64

In [26]:
def ITIT():    
    for feather in feathers:
        cat_name_d=pd.read_csv(feather+'_vec.csv')
        #print(cat_name_d.head)
        #cat_name=pd.Series(cat_name_d.iloc[:,0])
        print(feather,cat_name_d.head())
%timeit ITIT()

application_id            Unnamed: 0  0  1  2  3  4
0              anketa  0  0  0  0  1
1              mobile  0  0  0  1  0
2                 ncl  0  0  1  0  0
3    passport_metrics  0  0  1  0  1
4  retail-marketplace  0  0  1  1  0
event_type   Unnamed: 0  0  1  2
0         pv  0  0  0
1         se  0  1  0
2        err  1  0  1
3         sv  1  1  0
4         ue  1  1  1
event_category         Unnamed: 0  0  1  2  3  4  5  6  7  8
0               -1  0  0  0  0  0  0  0  0  1
1       Debit card  0  0  0  0  0  0  0  1  0
2        Ecommerce  0  0  0  0  0  0  0  1  1
3  Non-interaction  0  0  0  0  0  0  1  0  0
4     interactions  0  0  0  0  0  0  1  1  0
event_name             Unnamed: 0  0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  \
0                   -1  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   1   
1  Anketa::Step3::Send  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   1   
2                 View  0  0  0  0  0  0  0  0  0  0   0   0   0   0   1   0  

page_urlpath_full                          Unnamed: 0  0  1  2  3  4  5  6  7  8  9  10  11  12  \
0  03eb3ceab6204f8b602f1863f7fbce01  0  0  0  0  0  0  0  0  0  0   0   0   0   
1  0aab04d1c6960342cbee1a31a0680312  0  0  0  0  0  0  0  0  0  0   0   0   0   
2  0d1e93db443e0390c9b0b1304dec1548  0  0  0  0  0  0  0  0  0  0   0   0   0   
3  0eba7286124e9d64e4da904d9c0e9448  0  0  0  0  0  0  0  0  0  0   0   0   0   
4  113cb46e3be32ce3d9f1abd632e588f9  0  0  0  0  0  0  0  0  0  0   0   0   0   

   13  14  15  16  17  
0   0   0   0   0   0  
1   0   0   0   0   1  
2   0   0   1   0   1  
3   0   0   1   1   1  
4   0   1   0   1   0  
net_connection_type   Unnamed: 0  0  1
0         -1  0  0
1     mobile  0  1
2    offline  1  0
3       wifi  1  1
net_connection_tech   Unnamed: 0  0  1  2  3  4
0         -1  0  0  0  0  0
1      HSPA+  0  0  0  1  0
2        LTE  0  0  0  1  1
3   DC_HSPAP  0  0  1  0  1
4       EDGE  0  0  1  1  0
application_id            Unnamed: 0  0  1  2  3

event_label                          Unnamed: 0  0  1  2  3  4  5  6  7  8  9  10  11  12  \
0                                -1  0  0  0  0  0  0  0  0  0  0   0   0   0   
1  3ab8151284c7bdf8cabc5c699892ac53  0  0  0  0  0  0  0  0  0  0   0   0   0   
2  6dfcecd944a676e953de64fbb413bd97  0  0  0  0  0  0  0  0  0  0   0   0   0   
3  0677a454178da31547b2b1d3e7d76068  0  0  0  0  0  0  0  0  0  0   0   0   0   
4  2bac8fca54691479b5f5e0cfec7ee1c1  0  0  0  0  0  0  0  0  0  0   0   0   1   

   13  14  15  
0   0   0   1  
1   1   0   1  
2   1   1   0  
3   1   1   1  
4   1   0   1  
device_screen_name                   Unnamed: 0  0  1  2  3  4  5  6  7  8  9
0                         -1  0  0  0  0  0  0  0  0  1  0
1  Accounts And Cards Widget  0  0  0  0  0  0  0  0  1  1
2               All Payments  0  0  0  0  0  0  0  1  0  1
3        All payments screen  0  0  0  0  0  0  1  0  0  0
4      Card To Card Transfer  0  0  0  0  0  0  1  0  1  0
timezone            Unnamed: 0  

page_urlpath_full                          Unnamed: 0  0  1  2  3  4  5  6  7  8  9  10  11  12  \
0  03eb3ceab6204f8b602f1863f7fbce01  0  0  0  0  0  0  0  0  0  0   0   0   0   
1  0aab04d1c6960342cbee1a31a0680312  0  0  0  0  0  0  0  0  0  0   0   0   0   
2  0d1e93db443e0390c9b0b1304dec1548  0  0  0  0  0  0  0  0  0  0   0   0   0   
3  0eba7286124e9d64e4da904d9c0e9448  0  0  0  0  0  0  0  0  0  0   0   0   0   
4  113cb46e3be32ce3d9f1abd632e588f9  0  0  0  0  0  0  0  0  0  0   0   0   0   

   13  14  15  16  17  
0   0   0   0   0   0  
1   0   0   0   0   1  
2   0   0   1   0   1  
3   0   0   1   1   1  
4   0   1   0   1   0  
net_connection_type   Unnamed: 0  0  1
0         -1  0  0
1     mobile  0  1
2    offline  1  0
3       wifi  1  1
net_connection_tech   Unnamed: 0  0  1  2  3  4
0         -1  0  0  0  0  0
1      HSPA+  0  0  0  1  0
2        LTE  0  0  0  1  1
3   DC_HSPAP  0  0  1  0  1
4       EDGE  0  0  1  1  0
519 ms ± 13.2 ms per loop (mean ± std. dev. of 7

for feather in feathers:
    Cat_name=pd.read_csv(feather+'.csv')
    vec_cat=pd.DataFrame(np.eye(len(Cat_name['0']),dtype=np.int8),Cat_name['0'])
    vec_cat.to_csv(feather+'_vec'+'.csv', index=False)
    print((pd.read_csv(feather+'_vec'+'.csv')))

In [25]:
cat_O=pd.read_csv('page_urlpath_full'+'.csv')
for i in range(len(cat_O)):
    if cat_O.iloc[i].isnull().empty:
        print(cat_O.iloc[i].isnull())

In [76]:
pd.read_csv('event_name.csv')

0
0                                           NaN
1                           Anketa::Step3::Send
2                                          View
3                              auto card change
4                                         click
...                                         ...
83158        Main Page::Верхний баннер 2::click
83159                 Main Page::Ипотека::click
83160             Main Page::Промоблок 2::click
83161  Main Page::Рассчитайте свой кредит::Send
83162                       Catalog::РЖД::Click

[83163 rows x 1 columns]

In [80]:
En=pd.read_csv('event_name.csv')
t=0
for i in En.values:
    t=t+str(i).count('view')
t

12

In [43]:
cat_name_s=Cat_names['0']
cat_names_s

NameError: name 'cat_names_s' is not defined

In [47]:
vec_app_id_u=pd.DataFrame(np.eye(len(Cat_names['0'])),Cat_names['0'])

In [94]:
a=[]
for i in product([1,0],repeat=18):
    a.append(i)
n=np.array(a)
np.reshape(n, (-1,18))

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
a

In [58]:
q=np.eye(5)

In [81]:
q=np.eye(6)
for i in range(1,len(q)+1,1):
    #n=q[i,:]+q[i+1]
    q=np.vstack([q,np.eye(6,k=i)])
print(q)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [54]:
vec_app_id_u.to_csv('app_id_u.csv', index=False)

In [55]:
(pd.read_csv('app_id_u.csv')).iloc[0,0]

1.0

In [56]:
vec_app_id_u.iloc[0,0]

1.0